[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "test/contracts"
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = true
gas_limit = "999999999999"

# Base mainnet
[rpc_endpoints]
base = "https://mainnet.base.org"
base_sepolia = "https://sepolia.base.org"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
